@startuml
title Downloading a file
|oseoserver|
start
    :HTTP request to serve_http view;
    :extract relevant file parameters;
    :find matching oseoFile;
    if (oseoFile found?) then (no)
        :HTTP 404 (resource not found);
    else (yes)
        if (oseoFile available?) then (no)
            |oseoserver|
            :HTTP 4?? (resource not available);
            stop
        else (yes)
            |custom download handler|
            :retrieve the file from disk;
        endif
    |oseoserver|
        :update oseoFile download count;
        :update oseoFile availability;
        if (delete after downloaded?) then (no)
        else (yes)
    |custom download handler|
            :delete file from disk;
        endif
    |oseoserver|
        :return file;
    endif
stop
@enduml
